[package]
name = "bevy_polyline"
version = "0.1.0"
edition = "2018"

[[example]]
name = "linestrip"
path = "examples/linestrip.rs"

[[example]]
name = "nbody"
path = "examples/nbody.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "997eae61854b362c10810884966ac605121e04d7" }

[dev-dependencies]
lazy_static = "1.4.0"
rand = "0.8.3"
ringbuffer = "0.8.2"

[patch.crates-io]
# bevy = { path = "../bevy" }
# wgpu = { path = "../wgpu-rs/" }
# wgpu-types = { path = "../wgpu/wgpu-types" }
# wgpu-core = { path = "../wgpu/wgpu-core" }
